apiVersion: apps/v1
kind: Deployment
metadata:
  name: shift-remote-demo-spring-dep
spec:
  selector:
    matchLabels:
      app: shift-remote-demo-spring
  replicas: 1
  template:
    metadata:
      labels:
        app: shift-remote-demo-spring
    spec:
      containers:
      - name: shift-remote-demo-spring
        image: zmargeta/shift-remote-demo-spring:latest
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: "1"
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /system/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /system/health
            port: http
          failureThreshold: 6
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /system/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: shift-remote-demo-spring-svc
spec:
  ports:
  - port: 8080
    targetPort: http
  selector:
    app: shift-remote-demo-spring
