apiVersion: apps/v1
kind: Deployment
metadata:
  name: shift-remote-demo-spring-dep
  labels:
    app: shift-remote-demo-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shift-remote-demo-spring
  template:
    metadata:
      labels:
        app: shift-remote-demo-spring
    spec:
      containers:
      - name: shift-remote-demo-spring-pod
        image: zmargeta/shift-remote-demo-spring
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shift-remote-demo-spring-svc
  labels:
    app: shift-remote-demo-spring
spec:
  ports:
  - port: 8080
    targetPort: "http"
  selector:
    app: shift-remote-demo-spring
